import type { Metadata } from "next";
import { Inter, Pacifico,Fira_Sans } from "next/font/google";
import "./globals.css";
import SessionProvider, { SessionContext } from "./layouts/sessionProvider";
import { validateSession } from "@/lib/auth";
import { EdgeStoreProvider } from "./layouts/edgestoreProvider";

const sans = Fira_Sans({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await validateSession();

  return (
    <html lang="en">
      <SessionProvider value={session as SessionContext}>
        <EdgeStoreProvider>
          <body className={sans.className}>{children}</body>
        </EdgeStoreProvider>
      </SessionProvider>
    </html>
  );
}
